const CONTAINER = {
  CONTAINER_PADDING_XS: 15,
  CONTAINER_PADDING_XL: 20
}

const BREAKPOINTS = {
  BREAKPOINTS_XS: 375,
  BREAKPOINTS_SM: 576,
  BREAKPOINTS_MD: 768,
  BREAKPOINTS_LG: 992,
  BREAKPOINTS_XL: 1200,
  BREAKPOINTS_2XL: 1400,
  BREAKPOINTS_3XL: 1600,
  BREAKPOINTS_4XL: 1800,
}

const VAR = {
  ...BREAKPOINTS,
  ...CONTAINER
};
export default VAR;
